Action: To generate the lib types when pushed to master
muhammadsammy/tailwindcss-classnames pull request #219
Opened 2021-05-10 22:10 UTC by imrishabh18

Issue - #172

2021-05-10 23:16 UTC, muhammadsammy reviewed
That should do it but, it won't commit the changes made by `yarn generate` to git.
I would suggest you add another step to commit these changes using   https://github.com/marketplace/actions/add-commit or https://github.com/marketplace/actions/git-auto-commit or any other similar actions

2021-05-14 19:38 UTC, muhammadsammy commented on .github/workflows/release.yml
> +          commit_message: Commit yarn generated files
Please change this commit message to something like this "chore: generate library types" to be compatible with the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

2021-05-14 19:48 UTC, muhammadsammy requested changes
Everything looks good but please change the commit message in auto-commit action to something like: 
`chore: generate library types` to be compatible with the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec. Thank you!

2021-05-14 19:53 UTC, muhammadsammy reviewed
Also, please change your commit messages to start with `chore:` or `chore(ci):` prefix 
to be compatible with Conventional Commits so I can rebase merge your PR instead of squashing your commits

2021-05-14 22:01 UTC, muhammadsammy approved these changes
That's great. Thank you, @imrishabh18 !
Could you please rewrite/rename your commit messages to adhere with the Conventional Commits spec or would you rather me to squash them into one commit?

2021-05-14 22:04 UTC, imrishabh18 commented
Sorry! Isn't this the conventional commit `chore: rename commit message ` style? Maybe I missed something you can squash the commits

2021-05-14 22:22 UTC, muhammadsammy commented
I was referring to other commits in your commit history in this PR, 7ad38c3aa0afd022b392923844619fa911bb3057 and bf283e6a4a9d706b8ea05e44399c661297495b37 are not adhering to the conventional commit spec so I can't rebase them into master.

Thanks again for contributing :smile:

2021-05-14 22:23 UTC, merged